services:

  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'Europe/Paris'
    # Volumes store your data between container upgrades
    volumes:
      - './wallos/db:/var/www/html/db'
      - './wallos/logos:/var/www/html/images/uploads/logos'
    networks:
      - medias_network
    restart: unless-stopped

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: unless-stopped
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MEDIA_STORAGE_PATH}:/mnt/medias

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      - medias_network
      - elastic
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=Europe/Paris
      - VERSION=docker
      - PLEX_CLAIM={PLEX_CLAIM}
    volumes:
      - ./plex/library:/config
      - ./plex/tvseries:/tv
      - ./plex/movies:/movies
      - ${MEDIA_STORAGE_PATH}:/mnt/medias
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
    ports:
      - 5055:5055
    networks:
      - medias_network
    volumes:
      - ./jellyseerr:/app/config
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${MEDIA_STORAGE_PATH}:/mnt/medias
      - ./prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - medias_network
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./sonarr:/config
      - ./sonarr/tv:/tv #optional
      - ./sonarr/downloads:/downloads #optional
      - ${MEDIA_STORAGE_PATH}:/mnt/medias
    ports:
      - 8989:8989
    networks:
      - medias_network
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./radarr:/config
      - ./radarr/movies:/movies #optional
      - ./radarr/downloads:/downloads #optional
      - ${MEDIA_STORAGE_PATH}:/mnt/medias
    ports:
      - 7878:7878
    networks:
      - medias_network
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./nzbget:/config
      - ${MEDIA_STORAGE_PATH}/nzbget/downloads:/downloads #optional
      - ${MEDIA_STORAGE_PATH}:/mnt/medias
    ports:
      - 6789:6789
    networks:
      - medias_network
    restart: unless-stopped

networks:
  medias_network:
    driver: bridge
  elastic:
    external: true
